# Site
repository: GatlingPeaShooter/YuqiChen.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yuqi Chen
title: Phd Student in Washington University in St. Louis
email: chen.yuqi@wustl.edu

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  GatlingPeaShooter

download_link: "https://GatlingPeaShooter.github.io/YuqiChenCV/YuqiChen CV.pdf"


# About Section
# about_title: About Me
about_profile_image: images/Photo of Chen yuqi.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yuqi Chen and I'm currently a Ph.D student. Now, my research interest is in <mark>Personalized Large Language Models(LLM)</mark>.

  My prior research area: <mark>Sentiment Analysis</mark> and <mark>Information Extraction</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bachelor, Xidian University
        caption: 2015 - 2019
        sub_title:  School of Aerospace Scienceand Technology, TsienHsueshen experimental class.
        Major: Space Science and Technology
        quote: >
          Established in 1931, Xidian is famous for its specialty in electronics and information technology, and for its excellent education and research capabilities in electronics-related disciplines such as communications engineering and electrical engineering.
        description: | # this will include new lines to allow paragraphs
          During my time at Xidian I learnt most of my key skills that have been useful even now, such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        Honor: Second Prize of China-Russia Universities Small Satellite Innovation Design Competition

      - layout: left
        title:  Master, University of Chinese Academy of Sciences
        caption: 2019 - 2022
        sub_title: Aerospace Information Research Institute.
        Major: Natural Language Processing, mainly in Information Extraction
        quote: > 
          The University of Chinese Academy of Sciences (UCAS) is a public general institution of higher education affiliated with the Chinese Academy of Sciences (CAS), with the Graduate School of the University of Science and Technology of China (USTC), the predecessor of which was established in 1978, and is the first graduate school in mainland China, training up the first Doctor of Science (Ph.D.), first Doctor of Engineering (Ph.D.), first female Ph.D., and the first double-degree Ph.
        description: | # this will include new lines to allow paragraphs
          During this time I was introduced to research on a large scale, from the first time I read a paper, the first time I reproduced methods, the first line of experimental code I wrote, to eventually the first time I wrote my own papers and the first time my papers were accepted. This experience is one of my most precious memories.
          
          And i published two papers in this period, check section Publications for details.

      - layout: left
        title:  Ph.D, Washington University in St. Louis
        caption: 2024 - current
        sub_title: McKelvey School of Engineering.
        Major: LLMs, mainly in personalized LLM.
        quote: >
          Washington University in St. Louis (WashU) is a private research university in St. Louis, Missouri, United States. Established in 1853 by a group of civic leaders, it was named for George Washington.
        description: | # this will include new lines to allow paragraphs
          This was my first study abroad experience, and it was also the first time I experienced a different way of thinking about research. Changing to a new field put me at the starting point once again, asking questions with the trouble I met, and even going so far as to make every mistake that a beginner has ever made. I am looking forward to the person I will be when I graduate years from now.

  - title: Work
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  Xizhi AI Education.
        caption: 2022 - 2024
        sub_title: Software Engineer Internship.
        Major: Visually Rich Document Information Extraction.
        quote: >
          Xizhi AI Education is a company dedicated to the development of automated problem solving models, famous for develop Eva Tutor App.
        description: | # this will include new lines to allow paragraphs
          I was responsible for extracting certain important information from the user's questions to use as input for the solution model. 
          After the emergence of LLMs, I was responsible for experiments with prompt and locally deploy of some models.

  - title: Publications
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - [Chen Y, Zhang Z, Zhou G, et al. Span-based dual-decoder framework for aspect sentiment triplet extraction[J]. Neurocomputing, 2022, 492: 211-221.](https://www.sciencedirect.com/science/article/abs/pii/S0925231222003897)
      - [Chen Y, Keming C, Sun X, et al. A Span-level Bidirectional Network for Aspect Sentiment Triplet Extraction[C]//Proceedings of the 2022 Conference on Empirical Methods in Natural Language Processing. 2022: 4300-4309.](https://aclanthology.org/2022.emnlp-main.289.pdf)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AIs, some of my other interests and hobbies are:
      - Ping-pong
      - Gaming

#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
